/* Generated by Cython 0.29.22 */

#ifndef __PYX_HAVE__PythonFromC
#define __PYX_HAVE__PythonFromC

#include "Python.h"

#ifndef __PYX_HAVE_API__PythonFromC

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C double getPi(int __pyx_skip_dispatch);
__PYX_EXTERN_C double getE(void);

__PYX_EXTERN_C float PI;

#endif /* !__PYX_HAVE_API__PythonFromC */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initPythonFromC(void);
#else
PyMODINIT_FUNC PyInit_PythonFromC(void);
#endif

#endif /* !__PYX_HAVE__PythonFromC */
